#application: proven-electron-569
application: beegoapp2
version: 1
runtime: go
api_version: go1

handlers:

- url: /static/css
  static_dir: static/css
  mime_type: "text/css"

- url: /.*
  script: _go_app
  
